### ISSUE TITLE
Bluetooth DOS app

### ISSUE THREAD

**Issue by rohanday3** [Flipper-XFW/Xtreme-Apps#9]
Is it possible to create an app that could flood ping/connect packets to dos bt devices?

**Comment by WillyJL** [comment]
this is not wifi where you have deauth.

**Comment by rohanday3** [comment]
You don't need to deauth, you can send alot of data packets with no delay and some devices that don't have alot of memory like a Bluetooth speaker will get DoS'd. You can do it on Linux with L2Ping
```
l2ping -s 600 -f <MA:CA:DD:RE:SS>
```
https://github.com/crypt0b0y/BLUETOOTH-DOS-ATTACK-SCRIPT
